Conversion for `aten.index.Tensor_hacked_twin` -> `tcp.custom_op` (#3)
This is useful for ML ranker C7:
```
ERROR: [RoboCompiler] - RoboCompiler step 'RoboCompiler Optimize' failed with the following error:
cruise/mlp/robotorch/project/trajectory_ranking/model_architectures/per_npc_ranker.py:712:0: error: failed to legalize operation 'torch.aten.index.Tensor_hacked_twin' that was explicitly marked illegal
```
TorchToTosa doesn't match the AtenIndexTensorHackedTwinOp due to [this](https://sourcegraph.robot.car/github.robot.car/cruise/mla-robocomp-torch-mlir/-/blob/lib/Conversion/TorchToTosa/TorchToTosa.cpp?L3788) constraint:
```
    // Right now only support multiple indexes with same shape
    // TODO for different shape multiple indexes, add broadcast_to for small
    // shape
    for (auto indexShapeOneDim : indexesShape) {
      if (!llvm::equal(indexesShape[0], indexShapeOneDim)) {
        return rewriter.notifyMatchFailure(
            op, "unimplemented: Only support multi indexes with same shape");
      }
    }
```
where we see multiple index tensors of different shapes:
```
%278 = torch.prim.ListConstruct %277, %273, %270, %205 : (!torch.vtensor<[1,1,1,1],si64>, !torch.vtensor<[24,1,1],si64>, !torch.vtensor<[2,1],si64>, !torch.vtensor<[40],si64>) -> !torch.list<vtensor> 
%279 = torch.aten.index.Tensor_hacked_twin %arg9, %278 : !torch.vtensor<[1,24,2,40],f32>, !torch.list<vtensor> -> !torch.vtensor<[1,24,2,40],f32>
```
We can dig into supporting this case in TorchToTosa eventually, however this is to unblock the immediate case for C7 where we plan to map this to a data movement kernel (like gather).